#!/bin/bash
apt-get update -o Acquire::AllowInsecureRepositories=true -o Acquire::AllowDowngradeToInsecureRepositories=true
apt-get install -y --allow-unauthenticated libgbm1 libnss3 libxss1 libasound2 libatk-bridge2.0-0 libgtk-3-0
