#!/bin/bash
sed -i 's|deb.debian.org/debian-security|archive.debian.org/debian-security|g' /etc/apt/sources.list
sed -i 's|security.debian.org|archive.debian.org|g' /etc/apt/sources.list
sed -i '/bullseye-security/{ s/^/# / }' /etc/apt/sources.list
apt-get update -o Acquire::Check-Valid-Until=false
apt-get install -y --no-install-recommends libgbm1 libnss3 libxss1 libasound2 libatk-bridge2.0-0 libgtk-3-0 libglib2.0-0
